services:
  meilisearch:
    image: docker.io/getmeili/meilisearch:v1.13.0 # we have to use it because migration got easier
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=fancy_master_key
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=/data.ms
      - MEILI_EXPERIMENTAL_ENABLE_METRICS=true
      - MEILI_EXPERIMENTAL_ENABLE_VECTORS=true
    ports:
      - ${MEILI_PORT:-7700}:7700
    cap_add: # needed to work smoothly on rootless Ubuntu 24.04
      - DAC_OVERRIDE # feel free to remove it if you are not using Ubuntu 24.04
    networks:
      - meilisearch
    volumes:
      - ./data.ms:/data.ms:U
    restart: unless-stopped
    #env_file:
    #  - ../.env    

networks:
  meilisearch:
    driver: bridge